# Project version
version=1.0.0

# Kotlin version
kotlin.version=2.0.0

# Compose version
compose.version=1.6.10

# Android
android.compileSdk=34
android.minSdk=24
android.targetSdk=34
android.useAndroidX=true

# JVM
jvm.target=17

# KMP
kmp.enabled=true

# Memory settings for Kotlin Wasm compilation
org.gradle.jvmargs=-Xmx6g -XX:+UseParallelGC
org.gradle.java.home=/opt/homebrew/opt/openjdk@21
kotlin.daemon.jvmargs=-Xmx6g
kotlin.jvm.target.validation.mode=warning
